import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Link from "next/link";
// ----------------------- root layout -------------------------------
const inter = Inter({ subsets: ["latin"] });
// contain whole application layout
// contains meta data
export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

// nothing but a functional component
//  not only design purpose, we can keep anything in layout that we want at whole application
// export default function RootLayout({
export default function MainLayout({
  // any name
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className="p-6">
      <body className={inter.className}>
        <nav>Home | About</nav>
        <nav className="mt-6 ">
          <ul className="flex justify-evenly">
            <li><Link href={`/`}>Home</Link> </li>
            <li><Link href={`/about`}>| About</Link></li>
            <li><Link href={`/blogs`}>| Blogs</Link></li>
            {/* <li><Link prefetch={false} href={`/about`}>| About</Link></li> */}
          </ul>
        </nav>
        {children}
        {/* children --> current page content */}
        <footer>all right reserved</footer>
      </body>
    </html>
  );
}
